image:
  file: .gitpod.Dockerfile
  context: .gp
ports:
- port: 8001
  onOpen: notify
- port: 8002
  onOpen: notify
- port: 5432
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- init: . ${GITPOD_REPO_ROOT}/.gp/install.Unix.sh
- name: Logs
  command: >
    mysqld --daemonize;
    apachectl start;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log -I /var/log/nginx/access.log -I /var/log/nginx/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log;
- name: Terminal
  command: >
    clear;
    echo "Commands:";
    echo " * apachectl start";
    echo " * apachectl stop";
    echo " * mysqld --daemonize";
    echo " * mysqladmin -u root shutdown -p";