name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: php-advanced/lec-02/phpunit-tests

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
  
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./php-advanced/lec-02/phpunit-tests

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phpunit-tests" #Must be unique in Heroku
          heroku_email: "felipealencarlopes@gmail.com"
          branch: master
          appdir: "./php-advanced/lec-02/phpunit-tests"
          dontuseforce: false

